services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - 5006:5006
    environment:
    - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
    - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
    - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
    - ACTUAL_OPENID_DISCOVERY_URL=${AUTH_URL}
    - ACTUAL_OPENID_CLIENT_ID=${CLIENT_ID}
    - ACTUAL_OPENID_CLIENT_SECRET=${CLIENT_SECRET}
    - ACTUAL_OPENID_SERVER_HOSTNAME=${HOSTNAME}
    volumes:
      - /opt/appdata/actual:/data
    networks:
      - warptunnel
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.entryPoints=https
      - traefik.http.routers.actual.rule=Host(`budget.hostname.org`)
networks:
  warptunnel:
    external: true
