services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: always
    container_name: redlib
    ports:
      - 3030:8080 # Specify `127.0.0.1:8080:8080` instead if using a reverse proxy
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    env_file: 
      - path: ./redlib.env
    networks:
      - warptunnel
    labels:
      - traefik.enable=true
      - traefik.http.routers.redlib.entryPoints=https
      - traefik.http.routers.redlib.rule=Host(`reddit.hostname.org`)
    healthcheck:
      disable: true
networks:
  warptunnel:
    external: true
